# Generated by Django 4.2.1 on 2024-04-07 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refer', '0002_alter_code_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='end_at',
        ),
        migrations.AddField(
            model_name='code',
            name='referals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referals', to=settings.AUTH_USER_MODEL),
        ),
    ]
